#GOAL
#WRITE PROGRAM TO PLAY ROCK PAPER SCISSORS

Sus = 0

#PROMPT PLAYER TO PICK ROCK PAPER OR SCISSORS IF IT DOES NOT MEET ANY CHOICES PROMPT AGAIN

#STORE PLAYER CHOICE IN A VARRIABLE AND SCORE IN A VARRIABLE

#HAVE PC PICK RANDOM BETWEEN 1-3 NO DECIMALS AND STORE THAT IN A VARRIABLE

#HERES THE HARD SHIT AND THERES PROBABLY BETTER WAY TO DO IT
#WRITE A LIST OF A MILLION COMPARISONS (THERES PROBABLY A BETTER WAY TO DO THIS I MIGHT LOOK ONLINE OR GO IN A DISCORD)

#basically if player variable is X and PC is y ADD +1 to winner if x = y print draw, and try again